name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Derive version from tag
        id: ver
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          echo "version=$TAG" >> $GITHUB_OUTPUT
      - name: Publish + (optionally) auto-release
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.ver.outputs.version }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASS }}
        run: ./gradle --no-daemon wrapper && ./gradlew --no-daemon publishToMavenCentral
      # If you enabled publishToMavenCentral(true), publication auto-releases.
      # Otherwise, log in to the Sonatype Central Portal and click "Publish".
